### ISSUE TITLE
As a Admin User when I click on Investigators in Drawer I should navigate to Investigators page

### ISSUE THREAD

**Issue by agentmilindu** [scorelab/OpenDF#66]
Investigators page have the list of Investigators. Use the OpenDF REST API to get details

**Sub-tasks**

- [ ] When I navigate to Investigators page I should see the list of Investigators
- [ ] When I click on add Investigator, I should navigate to Add New Investigator page.
- [ ] When I click remove Investigator, I should navigate to Remove Investigator page.
